#!/usr/bin/env python3.8
"""
Windows process kill

Usage:
    pkill --cname-whitelist=FILE --path-whitelist=FILE
"""
from utils.ps import ps_filter
from docopt import docopt


if __name__ == "__main__":
    args = docopt(__doc__)
    exe_path_wl = open(args["--path-whitelist"]).read().splitlines()
    exe_cname_wl = open(args["--cname-whitelist"]).read().splitlines()
    ps_filter(exe_path_wl, exe_cname_wl)
