#!/usr/bin/env python3.8
"""
Usage:
    smartlock <config_file> [-A=ACTION] [--dry-run] [-R] [--time=TIME] [options]

Options:
    -s --dry-run
    -t --time=TIME
    -R --remote-time
    -A --action=ACTION
    -L --list-actions
"""
from typing import *
from utils.executor import Executor
from utils.action import Action, compute_actions
from utils.config import Config
from utils.remote_time import get_remote_utc_datetime
from docopt import docopt
import datetime as dt
import os
import logging
import yaml
import requests


def is_activity_positive(url: Optional[str]) -> Optional[bool]:
    if not url:
        return None
    try:
        return requests.get(url).json()
    except:
        return False


def get_now(timezone, use_remote: Optional[bool], parse_time: Optional[str]):
    now = dt.datetime.now().astimezone(timezone)

    if use_remote:
        now = get_remote_utc_datetime().astimezone(timezone)

        if now is not None:
            return now
        
    if parse_time:
        time = dt.datetime.strptime(parse_time, "%H:%M")
        now = now.replace(hour=time.hour, minute=time.minute)

    return now


def main(args):
    if args["--list-actions"]:
        print("\n".join(action.name for action in Action))
        return

    logging.basicConfig(level=logging.DEBUG)

    config = Config.parse_file(args["<config_file>"])
    env = {**os.environ, **config.env, "SMARTLOCK_PATH": os.path.dirname(os.path.abspath(__file__))}
    exe = Executor(config.shell, encoding=config.shell_encoding, dry_run=args["--dry-run"], env=env)

    now = get_now(config.timezone, use_remote=args["--remote-time"], parse_time=args["--time"])
    logging.debug("Now is %s" % now)

    if args["--action"]:
        exe.print_exec(config.commands[args["--action"]])
        return

    actions = compute_actions(
        now,
        is_activity_positive=is_activity_positive(config.is_activity_allowed_url),
        allowed_activity_periods=config.allowed_activity_periods,
        danger_periods=config.danger_periods,
        critical_periods=config.critical_periods,
        allow_all_periods=config.allow_all_periods,
        dinner_periods=config.dinner_periods,
    )
    logging.debug(" ".join(action.name for action in actions))

    for action in actions:
        exe.print_exec(config.commands[action.name])


if __name__ == "__main__":
    main(docopt(__doc__))
