#!/usr/bin/env python3
from datetime import datetime as Datetime
from datetime import time as Time
import os
import sys
import time


SUDO_FILE_PATH = "/etc/sudoers.d/x"
SUDO_FILE_CONTENT = "x ALL=(ALL:ALL) NOPASSWD:ALL"
SAFE_TIME_START = Time(0, 0)
SAFE_TIME_END = Time(23, 59, 59)


def unlock():
    with open(SUDO_FILE_PATH, "w") as sudoers:
        sudoers.write(SUDO_FILE_CONTENT)


def is_safe_time():
    return SAFE_TIME_START <= Datetime.now().time() <= SAFE_TIME_END


if is_safe_time():
    unlock()
    print("UNLOCKED")

    if len(sys.argv) > 1 and sys.argv[1] == "crontab~":
        os.rename('/etc/crontab', '/etc/crontab~%d' % time.time())
        print("CRONTAB MOVED")

else:
    print("FORBIDDEN")

